# -*- coding: utf-8 -*-
"""WindExtreme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFJYbFppaLvLIYumW91Zm2O3KGVFxX18
"""

import glob

files = sorted(glob.glob("/content/sample_data/safranForcVu_daily_nc.zip"))
files[:5]

import zipfile
from pathlib import Path

ZIP_WIND = "/content/sample_data/safranForcVu_daily_nc.zip"

ROOT = Path("/content/safran_wind")
ROOT.mkdir(exist_ok=True, parents=True)

with zipfile.ZipFile(ZIP_WIND, 'r') as z:
    z.extractall(ROOT)

print("Extracted to", ROOT)

import xarray as xr
from pathlib import Path

ROOT = Path("/content/safran_wind")

files = sorted(ROOT.glob("**/*.nc"))

print(files[:5])

file = str(files[0])

import xarray as xr

ds = xr.open_dataset(file)

print(ds)

files = sorted(ROOT.glob("**/*.nc"))

ds = xr.open_mfdataset(files, combine="by_coords")

wind = ds["Wind10m_max_ms"]

wind_monthly = wind.resample(time="ME").max()

print(wind_monthly)

wind_monthly = wind_monthly.sel(time=slice("2000-01-01", "2024-12-31"))

print(wind_monthly)

wind_france = wind_monthly.mean(dim=["y","x"])

print(wind_france)

import pandas as pd

df_wind = wind_france.to_dataframe().reset_index()

df_wind = df_wind[["time","Wind10m_max_ms"]]
df_wind.columns = ["date","WindExtreme"]

print(df_wind.head())

df_wind.to_excel("WindExtreme_France_2000_2024.xlsx", index=False)

import os

os.listdir("/content")

df_wind.to_excel("/content/sample_data/WindExtreme_France_2000_2024.xlsx", index=False)

import matplotlib.pyplot as plt

plt.style.use("seaborn-v0_8-whitegrid")

fig, ax = plt.subplots(figsize=(7,3.5))

ax.plot(df_wind["date"], df_wind["WindExtreme"],
        color="darkgreen",
        linewidth=1.5)

#ax.set_title("Monthly Wind Extreme Index for France (2000–2024)", fontsize=12)
ax.set_xlabel("Year")
ax.set_ylabel("Wind speed (m/s)")

plt.tight_layout()
plt.show()