# -*- coding: utf-8 -*-
"""11-15-25_RX5day.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aomMnwjviro_kfAjEyrQZO-zdLmoQF7A
"""

import zipfile
from pathlib import Path

ZIP_PREP = "/content/sample_data/PRECIP_TOTAL_daily_nc.zip"

ROOT = Path("/content/safran_raw")
ROOT.mkdir(exist_ok=True, parents=True)

# --- Extraction ---
for z in [ZIP_PREP]:
    with zipfile.ZipFile(z, 'r') as f:
        f.extractall(ROOT)
        print("Extrait →", z, "dans", ROOT)

for p in sorted(ROOT.glob("*")):
    print("-", p.name)

import xarray as xr

file = "/content/safran_raw/ForcPRECIP_TOTAL_daily_1987.nc"

ds = xr.open_dataset(file)

print(ds)

import xarray as xr
import glob

files = sorted(glob.glob("/content/safran_raw/ForcPRECIP_TOTAL_daily_*.nc"))

ds = xr.open_mfdataset(files, combine="by_coords")

precip = ds["PRECIP_TOTAL_mmday"]

roll5 = precip.rolling(time=5).sum()

rx5day_monthly = roll5.resample(time="ME").max()

print(rx5day_monthly)

rx5day_monthly = rx5day_monthly.sel(time=slice("2000-01-01", "2024-12-31"))

print(rx5day_monthly)

rx5day_france = rx5day_monthly.mean(dim=["y","x"])
print(rx5day_france)

import pandas as pd

df = rx5day_france.to_dataframe().reset_index()

df = df[["time","PRECIP_TOTAL_mmday"]]
df.columns = ["date","RX5day"]

df.to_excel("RX5day_France_2000_2024.xlsx", index=False)

print(df.head())

import matplotlib.pyplot as plt
import pandas as pd

plt.style.use("seaborn-v0_8-whitegrid")

fig, ax = plt.subplots(figsize=(8,4))

ax.plot(df["date"], df["RX5day"], color="steelblue", linewidth=1.5)

#ax.set_title("Monthly RX5day Index for France (2000–2024)", fontsize=14)
ax.set_xlabel("Year", fontsize=12)
ax.set_ylabel("RX5day (mm)", fontsize=12)

ax.tick_params(axis='both', labelsize=10)

plt.tight_layout()
plt.show()