# -*- coding: utf-8 -*-
"""12-05-2025_PEIGSE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFqrCie6I5NDS6yZQqpuhO_3ieormbW9
"""

import zipfile, os, shutil
import numpy as np
import pandas as pd
import xarray as xr
from pathlib import Path
ZIP_FAO = "/content/sample_data/FAO56_climate_base_monthly_1988_2024.zip"
DIR_FAO = "/content/sample_data/FAO56_climate_base_monthly_1988_2024"

if os.path.exists(DIR_FAO):
    shutil.rmtree(DIR_FAO)
os.makedirs(DIR_FAO)

with zipfile.ZipFile(ZIP_FAO, "r") as z:
    z.extractall(DIR_FAO)

NC_IN = f"{DIR_FAO}/FAO56_climate_base_monthly_1988_2024.nc"
ds = xr.open_dataset(NC_IN)

# Minimal physical  adjustements
# ============================================================
Rnl = xr.where(ds["Rnl_MJm2day"] < 0, 0.0, ds["Rnl_MJm2day"])
Rn  = ds["Rns_MJm2day"] - Rnl
Rs  = xr.where(ds["Rs_MJm2day"] > ds["Rso_MJm2day"],
               ds["Rso_MJm2day"], ds["Rs_MJm2day"])

ds = ds.assign(
    Rnl_MJm2day=Rnl,
    Rn_MJm2day=Rn,
    Rs_MJm2day=Rs
)

# ============================================================
# 3. ET0 FAO-56 Monthly (FORMULa ALLEN)
# ============================================================

T  = ds["Tmean_C"]
u2 = ds["Wind2m_mean_ms"]
es = ds["es_kPa"]
ea = ds["ea_kPa"]
Rn = ds["Rn_MJm2day"]
P  = ds["Pressure_kPa"]

# Soil heat flux(Monthly)
G = 0.0

# Slope of the saturation vapor pressure curve (kPa/°C)
Delta = 4098 * (0.6108 * np.exp(17.27 * T / (T + 237.3))) / (T + 237.3)**2

# Psychrometric constant (kPa/°C)
gamma = 0.000665 * P

# ET0 en mm/day (FAO-56 Allen and al.)
ET0_mmday = (
    (0.408 * Delta * (Rn - G)
     + gamma * (900.0 / (T + 273.0)) * u2 * (es - ea))
    /
    (Delta + gamma * (1.0 + 0.34 * u2))
).rename("ET0_mmday")

ET0_mmday.attrs["units"]  = "mm/day"
ET0_mmday.attrs["method"] = "FAO-56 Allen et al. (monthly, G=0)"

# Conversion to mm/month
days = ds["time"].dt.days_in_month
ET0_mm_month = (ET0_mmday * days).rename("ET0_mm_month")
ET0_mm_month.attrs["units"] = "mm/month"

# add to dataset
ds = ds.assign(
    ET0_mmday=ET0_mmday,
    ET0_mm_month=ET0_mm_month
)

#  NaN Contrôle (xarray → isnull)
print("NaN ET0 mensuel :", float(ds["ET0_mm_month"].isnull().mean()))

NC_OUT = f"{DIR_FAO}/FAO56_climate_base_monthly_1988_2024_ET0.nc"
ds.to_netcdf(NC_OUT)
ds.close()

# ============================================================
# 5. MAPPING ET0
# ============================================================
MAP_PATH = "/content/sample_data/mapping_8602_communes.csv"
OUT_DIR  = Path("/content/safran_communes_ET0_monthly")
OUT_DIR.mkdir(exist_ok=True)

mapping = pd.read_csv(MAP_PATH, sep=";")
mapping = mapping[["x","y","code_insee"]].drop_duplicates()
mapping["code_insee"] = mapping["code_insee"].astype(str).str.zfill(5)

ds = xr.open_dataset(NC_OUT)
da = ds["ET0_mm_month"]

years = np.unique(pd.to_datetime(da.time.values).year)

for y in years:
    print(f"ET0 {y}")
    da_y = da.sel(time=str(y))

    df_grid = (
        da_y.to_dataframe()
            .reset_index()[["time","x","y","ET0_mm_month"]]
            .rename(columns={"ET0_mm_month":"et0_mm"})
    )

    df = df_grid.merge(mapping, on=["x","y"], how="inner")

    df_comm = (
        df.groupby(["code_insee","time"], as_index=False)["et0_mm"]
          .mean()
    )

    outp = OUT_DIR / f"commune_monthly_et0_{y}.parquet"
    df_comm.to_parquet(outp, index=False, compression="snappy")

    print(
        "✔",
        "communes:", df_comm["code_insee"].nunique(),
        "NaN:", float(df_comm["et0_mm"].isna().mean())
    )

da = ds["ET0_mm_month"].sel(time=slice("1988-01-01", "2024-12-31"))

print(da.time.min().values, da.time.max().values)

import zipfile
from pathlib import Path

# --- Chemin du fichier ZIP ---
ZIP_PREP = "/content/sample_data/PRECIP_TOTAL_monthly.zip"

# --- Dossier de destination ---
ROOT = Path("/content/safran_raw")
ROOT.mkdir(exist_ok=True, parents=True)

# --- Extraction ---
for z in [ZIP_PREP]:
    with zipfile.ZipFile(z, 'r') as f:
        f.extractall(ROOT)
        print("Extrait →", z, "dans", ROOT)

from pathlib import Path

ROOT = Path("/content/safran_raw")

for p in ROOT.rglob("*"):
    print(p)

import xarray as xr
from pathlib import Path

ROOT = Path("/content/safran_raw")

files = sorted(ROOT.glob("ForcPRECIP_TOTAL_monthly_*.nc"))

ds = xr.open_mfdataset(files, combine="by_coords")

import numpy as np
import pandas as pd

time_index = pd.Index(ds.time.values)

if not time_index.is_unique:
    _, unique_idx = np.unique(time_index.values, return_index=True)
    ds = ds.isel(time=np.sort(unique_idx))

print(ds.data_vars)

P_month = ds["PRECIP_TOTAL_mm"]

P_month = P_month.sel(time=slice("1988-01-01", "2024-12-31"))

from pathlib import Path
import pandas as pd
import numpy as np
import xarray as xr

MAP_PATH = "/content/sample_data/mapping_8602_communes.csv"
OUT_DIR  = Path("/content/safran_communes_PRECIP_monthly")
OUT_DIR.mkdir(exist_ok=True)

mapping = pd.read_csv(MAP_PATH, sep=";")
mapping = mapping[["x", "y", "code_insee"]].drop_duplicates()
mapping["code_insee"] = mapping["code_insee"].astype(str).str.zfill(5)

years = np.unique(pd.to_datetime(P_month.time.values).year)

for y in years:
    print(f"PRECIP {y}")

    da_y = P_month.sel(time=str(y))

    df_grid = (
        da_y.to_dataframe()
            .reset_index()[["time", "x", "y", da_y.name]]
            .rename(columns={da_y.name: "precip_mm"})
    )

    df = df_grid.merge(mapping, on=["x", "y"], how="inner")

    df_comm = (
        df.groupby(["code_insee", "time"], as_index=False)["precip_mm"]
          .mean()
    )

    outp = OUT_DIR / f"commune_monthly_precip_{y}.parquet"
    df_comm.to_parquet(outp, index=False, compression="snappy")

    print(
        "✔ communes:", df_comm["code_insee"].nunique(),
        "NaN:", float(df_comm["precip_mm"].isna().mean())
    )

# ============================================================
# 6. CONSTRUCTION Of the water Balance D_t = P - ET0 (MUNICIPLITIES)
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

ET0_DIR    = Path("/content/safran_communes_ET0_monthly")
PRECIP_DIR = Path("/content/safran_communes_PRECIP_monthly")
OUT_DIR    = Path("/content/safran_communes_WB_monthly")
OUT_DIR.mkdir(exist_ok=True)

years = range(1988, 2025)

for y in years:
    print(f"WB {y}")

    f_et0 = ET0_DIR / f"commune_monthly_et0_{y}.parquet"
    f_pr  = PRECIP_DIR / f"commune_monthly_precip_{y}.parquet"

    df_et0 = pd.read_parquet(f_et0)
    df_pr  = pd.read_parquet(f_pr)

    df = (
        df_pr.merge(
            df_et0,
            on=["code_insee", "time"],
            how="inner"
        )
        .rename(columns={
            "precip_mm": "P_mm",
            "et0_mm": "ET0_mm"
        })
    )

    df["D_mm"] = df["P_mm"] - df["ET0_mm"]

    outp = OUT_DIR / f"commune_monthly_water_balance_{y}.parquet"
    df[["code_insee", "time", "D_mm"]].to_parquet(
        outp, index=False, compression="snappy"
    )

    print(
        "✔ communes:", df["code_insee"].nunique(),
        "NaN:", float(df["D_mm"].isna().mean())
    )

# ============================================================
# 7. SPEI-k (k = 3, 6, 12) by municipality – PERIODE 1988–2024
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path
from scipy.stats import genlogistic, norm

WB_DIR  = Path("/content/safran_communes_WB_monthly")
OUT_DIR = Path("/content/spei_communes")
OUT_DIR.mkdir(exist_ok=True)

K_LIST = [3, 6, 12]
YEARS  = range(1988, 2025)

# --- lecture WB complet ---
dfs = []
for y in YEARS:
    dfs.append(pd.read_parquet(WB_DIR / f"commune_monthly_water_balance_{y}.parquet"))
df = pd.concat(dfs, ignore_index=True)

df["time"] = pd.to_datetime(df["time"])
df = df.sort_values(["code_insee", "time"])

# --- calcul SPEI-k ---
for k in K_LIST:
    print(f"\n=== SPEI-{k} ===")

    df[f"D_k{k}"] = (
        df.groupby("code_insee")["D_mm"]
          .transform(lambda s: s.rolling(k, min_periods=k).sum())
    )

    out_rows = []

    for code, g in df.groupby("code_insee"):
        x = g[f"D_k{k}"].dropna()
        if len(x) < 30:   # seuil standard
            continue

        # Ajustement loi log-logistique (SPEI standard)
        c, loc, scale = genlogistic.fit(x.values)

        cdf = genlogistic.cdf(g[f"D_k{k}"], c, loc=loc, scale=scale)
        spei = norm.ppf(cdf)

        tmp = g[["code_insee", "time"]].copy()
        tmp[f"SPEI_{k}"] = spei
        out_rows.append(tmp)

    spei_df = pd.concat(out_rows, ignore_index=True)

    outp = OUT_DIR / f"SPEI_{k}_communes_1988_2024.parquet"
    spei_df.to_parquet(outp, index=False, compression="snappy")

    print(
        "✔ communes :", spei_df["code_insee"].nunique(),
        "| NaN :", float(spei_df[f"SPEI_{k}"].isna().mean())
    )

!ls /content
!ls /content/*parquet
!ls /content/**/SPEI_*_communes_1988_2024.parquet

import pandas as pd

f = "/content/spei_communes/SPEI_6_communes_1988_2024.parquet"

df = pd.read_parquet(f)

df["time"] = pd.to_datetime(df["time"])

print(df.head())
print(df.shape)

spei_fr = (
    df.groupby("time")["SPEI_6"]
      .mean()
      .reset_index()
)

spei_fr = spei_fr.sort_values("time")

print(spei_fr.head())
print(spei_fr.tail())

print("NaN :", spei_fr["SPEI_6"].isna().mean())

spei_fr = spei_fr[
    (spei_fr["time"] >= "2000-01-01") &
    (spei_fr["time"] <= "2024-12-01")
]

print(spei_fr.head())
print(spei_fr.tail())
print(len(spei_fr))

out_xlsx = "/content/SPEI6_france_2000_2024.xlsx"

spei_fr.to_excel(
    out_xlsx,
    index=False
)

print("OK :", out_xlsx)